### ISSUE TITLE
[Docker] Image is missing aws command line executable

### ISSUE THREAD

**Issue by aquamatthias** [someengineering/resoto#1168]
### Motivation

Accessing EKS clusters requires invoking the `aws` command. The kubeconfig file generated by AWS looks like this:

```
- name: arn:aws:eks:eu-central-1:882347060974:cluster/test 
  user: 
    exec: 
      apiVersion: client.authentication.k8s.io/v1beta1 
      args: 
      - --region 
      - eu-central-1 
      - eks 
      - get-token 
      - --cluster-name 
      - test 
      command: aws
```

### Desired Behavior

Users can use access k8s eks clusters without additional effort.

### Additional Context

https://aws.amazon.com/premiumsupport/knowledge-center/eks-cluster-connection/
